version: "3.8"
services:
  vallhalla:
    image: gisops/valhalla:3.3.0
    ports:
      - 8002:8002
    volumes:
      - custom_files:/custom_files

    environment:
      - tile_urls=https://download.geofabrik.de/asia/iran-latest.osm.pbf
      - server_threads=2  # determines how many threads will be used to run the valhalla server
      - use_tiles_ignore_pbf=True  # load existing valhalla_tiles.tar directly
      - build_elevation=False  # build elevation with "True" or "Force": will download only the elevation for areas covered by the graph tiles
      - build_admins=False  # build admins db with "True" or "Force" 
      - build_time_zones=False  # build timezone db with "True" or "Force"
      - build_tar=True  # build an indexed tar file from the tile_dir for faster graph loading times
      - force_rebuild=False  # forces a rebuild of the routing tiles with "True"

volumes:
  custom_files:

networks:
  default:
    name: Fare-calculator
    external: true
     